// База данных фильмов для каталога
const moviesDatabase = [
    // Популярные фильмы 2024
    {
        id: 1,
        title: 'Дюна: Часть вторая',
        year: 2024,
        rating: 8.2,
        genres: ['фантастика', 'приключения', 'драма'],
        description: 'Продолжение эпической саги о пустынной планете Арракис и молодом герое Полу Атрейдесе.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1318972.jpg',
        duration: '166 мин',
        country: 'США',
        director: 'Дени Вильнёв',
        videoUrl: 'https://www.youtube.com/watch?v=U2Qp5pL3ovA'
    },
    {
        id: 2,
        title: 'Оппенгеймер',
        year: 2023,
        rating: 8.5,
        genres: ['драма', 'биография', 'история'],
        description: 'История создания атомной бомбы глазами физика Роберта Оппенгеймера.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1399419.jpg',
        duration: '180 мин',
        country: 'США',
        director: 'Кристофер Нолан',
        videoUrl: 'https://www.youtube.com/watch?v=bK6ldnjE3Y0'
    },
    {
        id: 3,
        title: 'Барби',
        year: 2023,
        rating: 7.8,
        genres: ['комедия', 'фантастика', 'приключения'],
        description: 'Барби и Кен отправляются в реальный мир, чтобы найти свое место в жизни.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395802.jpg',
        duration: '114 мин',
        country: 'США',
        director: 'Грета Гервиг',
        videoUrl: 'https://www.youtube.com/watch?v=pBk4NYhWNMM'
    },
    {
        id: 4,
        title: 'Стражи Галактики. Часть 3',
        year: 2023,
        rating: 8.1,
        genres: ['фантастика', 'боевик', 'комедия'],
        description: 'Последнее приключение команды Стражи Галактики во главе со Старлордом.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395802.jpg',
        duration: '150 мин',
        country: 'США',
        director: 'Джеймс Ганн',
        videoUrl: 'https://www.youtube.com/watch?v=5WfTEZJnv_8'
    },
    {
        id: 5,
        title: 'Человек-паук: Паутина вселенных',
        year: 2023,
        rating: 8.7,
        genres: ['фантастика', 'боевик', 'мультфильм'],
        description: 'Майлз Моралес путешествует по мультивселенной, встречая разных пауков.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395803.jpg',
        duration: '140 мин',
        country: 'США',
        director: 'Хоаким Дос Сантос',
        videoUrl: 'https://www.youtube.com/watch?v=shW9i6k8cB0'
    },
    {
        id: 6,
        title: 'Джон Уик 4',
        year: 2023,
        rating: 7.9,
        genres: ['боевик', 'триллер', 'криминал'],
        description: 'Джон Уик сражается с Высшим советом, чтобы обрести свободу.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395804.jpg',
        duration: '169 мин',
        country: 'США',
        director: 'Чад Стахелски',
        videoUrl: 'https://www.youtube.com/watch?v=example6'
    },
    {
        id: 7,
        title: 'Аватар: Путь воды',
        year: 2022,
        rating: 7.8,
        genres: ['фантастика', 'приключения', 'драма'],
        description: 'Джейк Салли и его семья исследуют океаны Пандоры.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395805.jpg',
        duration: '192 мин',
        country: 'США',
        director: 'Джеймс Кэмерон',
        videoUrl: 'https://www.youtube.com/watch?v=example7'
    },
    {
        id: 8,
        title: 'Топ Ган: Мэверик',
        year: 2022,
        rating: 8.3,
        genres: ['боевик', 'драма'],
        description: 'Пит Митчелл возвращается в школу летчиков-истребителей.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395806.jpg',
        duration: '131 мин',
        country: 'США',
        director: 'Джозеф Косински',
        videoUrl: 'https://www.youtube.com/watch?v=example8'
    },
    {
        id: 9,
        title: 'Черная пантера: Ваканда навсегда',
        year: 2022,
        rating: 7.6,
        genres: ['фантастика', 'боевик', 'драма'],
        description: 'Ваканда сталкивается с новыми угрозами после смерти короля Т\'Чаллы.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395807.jpg',
        duration: '161 мин',
        country: 'США',
        director: 'Райан Куглер',
        videoUrl: 'https://www.youtube.com/watch?v=example9'
    },
    {
        id: 10,
        title: 'Доктор Стрэндж: В мультивселенной безумия',
        year: 2022,
        rating: 7.4,
        genres: ['фантастика', 'боевик', 'ужасы'],
        description: 'Доктор Стрэндж исследует мультивселенную и сталкивается с Вандой.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395808.jpg',
        duration: '126 мин',
        country: 'США',
        director: 'Сэм Рэйми',
        videoUrl: 'https://www.youtube.com/watch?v=example10'
    },
    {
        id: 11,
        title: 'Бэтмен',
        year: 2022,
        rating: 7.8,
        genres: ['боевик', 'криминал', 'драма'],
        description: 'Брюс Уэйн расследует серию убийств в Готэме.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395809.jpg',
        duration: '176 мин',
        country: 'США',
        director: 'Мэтт Ривз',
        videoUrl: 'https://www.youtube.com/watch?v=example11'
    },
    {
        id: 12,
        title: 'Тор: Любовь и гром',
        year: 2022,
        rating: 6.9,
        genres: ['фантастика', 'боевик', 'комедия'],
        description: 'Тор отправляется в путешествие, чтобы найти себя.',
        poster: 'https://kinopoiskapiunofficial.tech/images/posters/kp/1395810.jpg',
        duration: '119 мин',
        country: 'США',
        director: 'Тайка Вайтити',
        videoUrl: 'https://www.youtube.com/watch?v=example12'
    },
    // Классические фильмы
    {
        id: 13,
        title: 'Криминальное чтиво',
        year: 1994,
        rating: 8.9,
        genres: ['криминал', 'драма', 'триллер'],
        description: 'История двух бандитов, боксера и жены гангстера, переплетается в этом культовом фильме.',
        poster: 'https://via.placeholder.com/300x450/ff6b6b/ffffff?text=Pulp+Fiction',
        duration: '154 мин',
        country: 'США',
        director: 'Квентин Тарантино',
        videoUrl: 'https://www.youtube.com/watch?v=example13'
    },
    {
        id: 14,
        title: 'Крестный отец',
        year: 1972,
        rating: 9.2,
        genres: ['драма', 'криминал'],
        description: 'Эпическая история семьи Корлеоне и их влияния на американскую мафию.',
        poster: 'https://via.placeholder.com/300x450/4ecdc4/ffffff?text=Godfather',
        duration: '175 мин',
        country: 'США',
        director: 'Фрэнсис Форд Коппола',
        videoUrl: 'https://www.youtube.com/watch?v=example14'
    },
    {
        id: 15,
        title: 'Темный рыцарь',
        year: 2008,
        rating: 9.0,
        genres: ['боевик', 'криминал', 'драма'],
        description: 'Бэтмен сталкивается с Джокером в эпической битве за душу Готэма.',
        poster: 'https://via.placeholder.com/300x450/45b7d1/ffffff?text=Dark+Knight',
        duration: '152 мин',
        country: 'США',
        director: 'Кристофер Нолан',
        videoUrl: 'https://www.youtube.com/watch?v=example15'
    },
    {
        id: 16,
        title: 'Интерстеллар',
        year: 2014,
        rating: 8.6,
        genres: ['фантастика', 'драма', 'приключения'],
        description: 'Команда астронавтов отправляется в космос, чтобы найти новый дом для человечества.',
        poster: 'https://via.placeholder.com/300x450/4ecdc4/ffffff?text=Interstellar',
        duration: '169 мин',
        country: 'США',
        director: 'Кристофер Нолан',
        videoUrl: 'https://www.youtube.com/watch?v=example16'
    },
    {
        id: 17,
        title: 'Бегущий по лезвию 2049',
        year: 2017,
        rating: 8.0,
        genres: ['фантастика', 'драма', 'триллер'],
        description: 'Молодой репликант-детектив раскрывает секрет, который может погрузить общество в хаос.',
        poster: 'https://via.placeholder.com/300x450/ff6b6b/ffffff?text=Blade+Runner+2049',
        duration: '164 мин',
        country: 'США',
        director: 'Дени Вильнёв',
        videoUrl: 'https://www.youtube.com/watch?v=example17'
    },
    {
        id: 18,
        title: 'Однажды в Голливуде',
        year: 2019,
        rating: 7.6,
        genres: ['комедия', 'драма'],
        description: 'История актера и его каскадера в Голливуде 1969 года.',
        poster: 'https://via.placeholder.com/300x450/45b7d1/ffffff?text=Once+Upon+Time',
        duration: '161 мин',
        country: 'США',
        director: 'Квентин Тарантино',
        videoUrl: 'https://www.youtube.com/watch?v=example18'
    },
    {
        id: 19,
        title: 'Джентльмены',
        year: 2019,
        rating: 7.8,
        genres: ['криминал', 'комедия', 'боевик'],
        description: 'История американского эмигранта, который построил империю марихуаны в Лондоне.',
        poster: 'https://via.placeholder.com/300x450/ff6b6b/ffffff?text=Gentlemen',
        duration: '113 мин',
        country: 'США',
        director: 'Гай Ричи',
        videoUrl: 'https://www.youtube.com/watch?v=example19'
    },
    {
        id: 20,
        title: 'Наследие',
        year: 2018,
        rating: 7.2,
        genres: ['ужасы', 'триллер'],
        description: 'Семья сталкивается с ужасающими секретами в своем новом доме.',
        poster: 'https://via.placeholder.com/300x450/4ecdc4/ffffff?text=Hereditary',
        duration: '127 мин',
        country: 'США',
        director: 'Ари Астер',
        videoUrl: 'https://www.youtube.com/watch?v=example20'
    },
    // Российские фильмы
    {
        id: 21,
        title: 'Т-34',
        year: 2018,
        rating: 7.8,
        genres: ['боевик', 'драма', 'военный'],
        description: 'История советского танкиста, который сбегает из немецкого плена на танке Т-34.',
        poster: 'https://via.placeholder.com/300x450/45b7d1/ffffff?text=T-34',
        duration: '139 мин',
        country: 'Россия',
        director: 'Алексей Сидоров',
        videoUrl: 'https://www.youtube.com/watch?v=example21'
    },
    {
        id: 22,
        title: 'Левиафан',
        year: 2014,
        rating: 7.7,
        genres: ['драма'],
        description: 'История простого человека, который борется с коррупцией в маленьком городке.',
        poster: 'https://via.placeholder.com/300x450/ff6b6b/ffffff?text=Leviathan',
        duration: '142 мин',
        country: 'Россия',
        director: 'Андрей Звягинцев',
        videoUrl: 'https://www.youtube.com/watch?v=example22'
    },
    // Анимация
    {
        id: 23,
        title: 'Человек-паук: Через вселенные',
        year: 2018,
        rating: 8.4,
        genres: ['фантастика', 'боевик', 'мультфильм'],
        description: 'Майлз Моралес становится новым Человеком-пауком и встречает других пауков из мультивселенной.',
        poster: 'https://via.placeholder.com/300x450/4ecdc4/ffffff?text=Spider-Verse',
        duration: '117 мин',
        country: 'США',
        director: 'Боб Персичетти',
        videoUrl: 'https://www.youtube.com/watch?v=example23'
    },
    {
        id: 24,
        title: 'История игрушек 4',
        year: 2019,
        rating: 7.8,
        genres: ['мультфильм', 'комедия', 'приключения'],
        description: 'Вуди и Базз отправляются в новое приключение с новыми игрушками.',
        poster: 'https://via.placeholder.com/300x450/45b7d1/ffffff?text=Toy+Story+4',
        duration: '100 мин',
        country: 'США',
        director: 'Джош Кули',
        videoUrl: 'https://www.youtube.com/watch?v=example24'
    },
    // Документальные
    {
        id: 25,
        title: 'Мой учитель осьминог',
        year: 2020,
        rating: 8.1,
        genres: ['документальный'],
        description: 'Фридайвер заводит дружбу с осьминогом и изучает его поведение.',
        poster: 'https://via.placeholder.com/300x450/ff6b6b/ffffff?text=My+Octopus+Teacher',
        duration: '85 мин',
        country: 'ЮАР',
        director: 'Пиппа Эрлих',
        videoUrl: 'https://www.youtube.com/watch?v=example25'
    },
    {
        id: 26,
        title: 'Тигр: Король джунглей',
        year: 2021,
        rating: 7.9,
        genres: ['документальный', 'природа'],
        description: 'История тигра Амира и его борьбы за выживание в джунглях.',
        poster: 'https://via.placeholder.com/300x450/4ecdc4/ffffff?text=Tiger+King',
        duration: '90 мин',
        country: 'США',
        director: 'Эрик Гуд',
        videoUrl: 'https://www.youtube.com/watch?v=example26'
    }
];

// Экспорт для использования в других файлах
if (typeof module !== 'undefined' && module.exports) {
    module.exports = moviesDatabase;
}
